### ISSUE TITLE
Filter struct contains constant data

### ISSUE THREAD

**Issue by lukaslihotzki** [binaryfields/resid-rs#8]
The f0 array of Filter (8192 bytes) occupies most of the space in the Synth struct (8528 bytes on x86-64). The contents of f0 depend only on which of both models is selected, so f0 can be stored statically instead, using one of these approaches:
- Store f0 in the binary.
  - Add precomputed f0 to the repository, already done for one model in tests/data/spline_output.rs.
  - Compute f0 in build.rs.
  - Compute f0 in const fn. A readable implementation would need either https://github.com/rust-lang/rust/issues/57241 or https://github.com/rust-lang/rust/issues/67792 when switching to fixed-point arithmetic.
- Compute f0 in run-time once with lazy_static.

Both of these approaches could be implemented when adding a feature to enable lazy_static.

What do you prefer, @binaryfields?

**Comment by binaryfields** [comment]
Here are my thoughts.  If you have a strong preference for a difference choice, let me know. Thanks!

1a) I would lean towards #1a simply because we already store lookup tables for waveform generator.  (see WAVE 6581/8580 etc in src/data)

1b) i would stay away from codegen tools for this

1c) would be optimal but based on the tracking issue that you linked, they are still hashing out some fundamental issues (IEEE compliance vs host) so its a bit too early for that. It would be properly impressive if this could be computed during complication though. 

2) Lazy_static is interesting, but I don't know how it would behave in no_std environment. I had a version of zinc64 booting and running bare metal c64 emulator on rpi3 but i do remember running into issues with synchronization primitives. I guess if we find more uses for lazy_static, we could give it another shot.

Cheers!
